### ISSUE TITLE
[TCML] 논문 읽기

### ISSUE THREAD

**Issue by dreamgonfly** [YBIGTA/DeepNLP-Study#1]
https://arxiv.org/abs/1707.03141

논문을 읽고 이해 및 요약해보기

**Comment by Jooong** [comment]
라져!

**Comment by dreamgonfly** [comment]
@Jooong 이거 제가 할 일이에요 :) 자세한 설명은 스터디 시간에 하겠습니다

**Comment by dreamgonfly** [comment]
논문 요약 :
https://github.com/YBIGTA/DeepNLP-Study/wiki/%5BReview%5D-TCML-:-Temporal-Convolution-based-Meta-Learner
